packages:
  - 'full'
  - 'versions/17' 
  - 'versions/16' 
  - 'versions/15' 
  - 'versions/14' 
  - 'versions/13'
  - 'types/17'
  - 'types/16'
  - 'types/15'
  - 'types/14'
  - 'types/13'
  - 'enums/17'
  - 'enums/16'
  - 'enums/15'
  - 'enums/14'
  - 'enums/13' 