FROM node:12.18.2-alpine3.11
RUN apk --no-cache add git
RUN apk add --no-cache bash
RUN apk add --no-cache make
RUN apk add --update alpine-sdk
RUN apk --no-cache add python3

ENTRYPOINT ["/bin/bash"]
